### ISSUE TITLE
warning: can not find correspond node

### ISSUE THREAD

**Issue by justas200** [alibaba/alibaba-load-balancer-controller#10]
The service creates a loadbalancer, but targets are empty. I see the following logs:
```
I0409 11:58:03.937777       1 node_utils.go:124] node izj6cikhraaok2ccadccd6z not found 
I0409 11:58:03.937799       1 server_groups.go:506] controller/nlb-controller "msg"="warning: can not find correspond node izj6cikhraaok2ccadccd6z for endpoint 192.168.7.166" "service"="nginx-ingress/nginx-ingress-ingress-nginx-controller"
```

<img width="825" alt="Image" src="https://github.com/user-attachments/assets/a3ab5ba3-a218-4874-9281-23ac800e94c2" />

Here is my setup
```
              - command:
                  - /load-balancer-controller
                  - --cloud-config=/etc/kubernetes/config/cloud-config.conf
                  - --controllers=service
                  - --leader-elect-resource-name=nlb
                  - --configure-cloud-routes=false
```

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-zone-maps: "cn-hongkong-d:vsw-xxx,cn-hongkong-c:vsw-xxx"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
  name: nginx-lb
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  loadBalancerClass: "alibabacloud.com/nlb"
  type: LoadBalancer
```
