### ISSUE TITLE
如何在资源清单中配置ALB的转发规则呢？

### ISSUE THREAD

**Issue by ghost** [alibaba/alibaba-load-balancer-controller#4]
比如按照header和请求路径进行转发等功能，在ALB的文档中没有看到配置的例子。

**Comment by codefinger23** [comment]
高级转发能力还未发布在开源版本上，可以先尝试使用canary看能否满足需求 [通过注解实现灰度发布](https://github.com/alibaba/alibaba-load-balancer-controller/blob/main/docs/zh/usage.md#%E9%80%9A%E8%BF%87%E6%B3%A8%E8%A7%A3%E5%AE%9E%E7%8E%B0%E7%81%B0%E5%BA%A6%E5%8F%91%E5%B8%83)

**Comment by MinglanGao** [comment]
最新发布的alibaba-load-balancer-controller v1.2.0支持自定义转发规则，通过在alb.ingress.kubernetes.io/conditions.<Service的名称>注解中配置转发条件使用。关于您提到的按照header和请求路径进行转发，以下是一个简单的配置示例：
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
   alb.ingress.kubernetes.io/order: "1"
   alb.ingress.kubernetes.io/conditions.gray-hello: |
     [{
       "type": "Header",
       "headerConfig": {
          "key":"gray-hello",
           "values": [
              "value1",
              "value2"
           ]
       }
      }]
  name: gray-hello
spec:
  ingressClassName: alb
  rules:
   - http:
      paths:
      - path: /hello
        pathType: ImplementationSpecific
        backend:
          service:
            name: gray-hello
            port:
              number: 88
```
