### ISSUE TITLE
两条ingress转发相同的svc地址会创建重复的服务器组，能不能复用？

### ISSUE THREAD

**Issue by souzens** [alibaba/alibaba-load-balancer-controller#6]
我创建了两条ingress规则，不同的域名指向同一个svc地址

比如：
```
apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: demo-https-1
   namespace: default
 spec:
   ingressClassName: alb
   tls:
   - hosts:
     - demo.alb.ingress.top
   rules:
     - host: demo.alb.ingress.top
       http:
         paths:
           - backend:
               service:
                 name: demo-slb-in
                 port:  
                   number: 9080
             path: /
             pathType: Prefix
```

```
apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: demo-https-2
   namespace: default
 spec:
   ingressClassName: alb
   tls:
   - hosts:
     - demo2.alb.ingress.top
   rules:
     - host: demo2.alb.ingress.top
       http:
         paths:
           - backend:
               service:
                 name: demo-slb-in
                 port:  
                   number: 9080
             path: /
             pathType: Prefix
```

事实上会生成两个名字相同的服务器组，有没有可以复用同一个服务器组的配置？

<img width="875" alt="image" src="https://github.com/alibaba/alibaba-load-balancer-controller/assets/35559209/78d5da9e-c409-4a9f-9d27-8f1fff51baa7">
