### ISSUE TITLE
ListenerId is mandatory for this action

### ISSUE THREAD

**Issue by toshihirocarp** [alibaba/alibaba-load-balancer-controller#7]
Apply requestTimeout to an exists albconfig caused "Message: ListenerId is mandatory for this action" error.

Thanks.

**Comment by MinglanGao** [comment]
requestTimeout is a listening attribute, so it should be configured in the spec.listeners field of albconfig and specify the port and protocol of listener. Here is a simple configuration example:
```yaml
apiVersion: alibabacloud.com/v1
kind: AlbConfig
metadata:
  annotations:
  ......
spec:
  config:
    ......
  listeners:
  - port: 8080
    protocol: HTTP
    requestTimeout: 60
```
Additionally, this error often occurs when the listener ID cannot be obtained after the update of the listener fails. If the above answer does not solve your problem, you can provide more log information to assist in troubleshooting.
